[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
enumflags2 = "0.7.10"
indoc = "2.0.5"
itertools = "0.13.0"
rayon = "1.10.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
rustc-hash = "2.1.0"
thiserror = "2.0.6"
